### ISSUE TITLE
`From Lens Require Lens TC.TC.` lenses breaks ssreflect rewrite syntax `-!` *transitively*

### ISSUE THREAD

**Issue by Janno** [bedrocksystems/coq-lens#11]
The following fails with a syntax error but works just fine when line 2 is commented out. (Beware, you can "fix" this by bactracking to before line 2. Best to always restart Coq when debugging this.)
```coq
From Coq Require Import ssreflect.
From Lens Require Lens TC.TC.
Axiom eqax : forall {x}, 1 + x = x + 1.
Goal 1 + 1 + 1 + 1 = 4.
  rewrite -!eqax.
(* Syntax error: '*' or [tactic:ssrrwargs] or [oriented_rewriter] expected after 'rewrite' (in [tactic:simple_tactic]). *)
```

`rewrite -..` and `rewrite !..` still work. Only the combination breaks.

The worst part about this is that it breaks this rewrite syntax in all files that depend on a file which requires `TC.TC`. Not even `Import`; `Require` is enough.

**Comment by gmalecha** [comment]
Given that we don't define any notations at all. This is probably an upstream problem.

**Comment by gmalecha** [comment]
This is a smaller example:

```coq
Require  Import ssreflect.

From MetaCoq.Template Require Import Ast Loader.

Parameter a : nat.
Axiom aa : a = a + a.

Goal a + a + a + a+ a+ a + a = a.
  rewrite -!aa.
```

**Comment by Blaisorblade** [comment]
Fixed in Equations, IIUC...

**Comment by gmalecha** [comment]
Closing at this was fixed upstream.
