### ISSUE TITLE
Notation `_ & _` interferes with Coq's `sigT` notation

### ISSUE THREAD

**Issue by swasey** [bedrocksystems/coq-lens#23]
Example:
```
Require Lens.Lens.
Import Lens.LensNotations.
Fail Check {n : nat & uint}.
```

**Comment by gmalecha** [comment]
I guess that we could switch to using `&:` as the operator here.

**Comment by gmalecha** [comment]
This is now fixed on the bundled version https://github.com/bedrocksystems/BRiCk/tree/master/coq-lens
